name: Generate Artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  library:
    runs-on: [self-hosted, linux, x64]
    strategy:
      fail-fast: false
      matrix:
        config:
          - { toolchain: gcc, architecture: x86_64-linux-gnu }
          - { toolchain: gcc, architecture: x86_64-windows-gnu }
          - { toolchain: gcc, architecture: aarch64-linux-gnu }
          - { toolchain: gcc, architecture: aarch32-linux-gnu }
          - { toolchain: gcc, architecture: thumbv6m-none-eabi }
          - { toolchain: gcc, architecture: thumbv7em-none-eabi }
          - { toolchain: gcc, architecture: thumbv7em-none-eabihf}
          - { toolchain: gcc, architecture: thumbv7m-none-eabi }
          - { toolchain: gcc, architecture: thumbv8m.base-none-eabi }
          - { toolchain: gcc, architecture: thumbv8m.main-none-eabihf }
    env:
      preset: ${{ matrix.config.toolchain }}-${{ matrix.config.architecture }}
    steps:
      - uses: lukka/get-cmake@9e07ecdcee1b12e5037e42f410b67f03e2f626e1 # v4.2.1

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          repository: embetech-official/cmake-presets
          tag: v0.0.1
          fileName: CMakeUserPresets.json

      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: ${{ env.preset }}
          configurePresetAdditionalArgs: '["-DCRC_TESTS=0", "-DCRC_DOC=0", "-DCRC_EXAMPLES=0"]'
          buildPreset: ${{ env.preset }}-install

      - name: Upload library install directory
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: libring_buffer-${{ matrix.config.architecture }}
          path: |
            install/${{ env.preset }}/**
          if-no-files-found: error