name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * 1' # 🕙 Run at 10:15 every Monday

jobs:
  build_and_test:
    name: 🔨 Build & Test (native GCC)
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📚 Install Doxygen
        uses: ssciwr/doxygen-install@329d88f5a303066a5bd006db7516b1925b86350e # v2.0.1

      - name: 🛠️ Install CMake
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # v4.3.3

      - name: 🚀 Run CMake workflow
        uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        with:
          workflowPreset: 'native-gcc'
