name: Run Test Suite

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🛠️ Install CMake
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # v4.3.3

      - name: 🔧 Setup GCC toolchain
        uses: jmacheta/setup-gcc-toolchain@6c712f09af5efb677bc53e4dea195c60b66286e4 # v2.0.1
        with:
          toolchain: x86_64-gcc
          version: latest

      - name: 🧪 Build & test (ASan+UBSan)
        uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        with:
          workflowPreset: 'native-gcc-asan'
