name: Unit Tests

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

jobs:
  build_and_test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
      
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset native

      - name: Build tests
        run: cmake --build --preset ut

      - name: Test
        run: ctest --preset ut

      - name: Build release
        run: cmake --build --preset install

